version: '3.7'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MBAJK_URL:https://api.jcdecaux.com/vls/v1/stations?contract=maribor&apiKey=5e150537116dbc1786ce5bec6975a8603286526b
  frontend:
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    environment:
        - VITE_APP_BACKEND_URL=http://backend:8000
    ports:
      - 80:80
    depends_on:
        backend:
          condition: service_started