name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ develop ]

jobs:
  fetch_data:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry env use python3.10
          poetry install

      - name: Run fetch data script
        run: python src/data/fetch_data.py