name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MBAJK_URL: ${{ secrets.MBAJK_URL }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry env use python3.10
          poetry install
      - name: Run tests
        run: |
          poetry run pytest

  fetch_data:
    needs: test
    runs-on: ubuntu-20.04
    env:
      MBAJK_URL: ${{ secrets.MBAJK_URL }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry env use python3.10
          poetry install

      - name: Dvc pull
        run: |
          poetry run dvc pull -r origin

      - name: Run fetch data script
        run: |
          poetry run python src/data/fetch_data.py

      - name: Commit and push changes
        run: |
          poetry run dvc add data/raw/mbajk
          poetry run dvc push -r origin
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add .
#          git pull
#          git commit -a -m "Fetch data" --allow-empty
#          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}