name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ develop ]

jobs:
  fetch_data:
    runs-on: ubuntu-20.04
    env:
      MBAJK_URL: "https://api.jcdecaux.com/vls/v1/stations?contract=maribor&apiKey=5e150537116dbc1786ce5bec6975a8603286526b"

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry env use python3.10
          poetry install

      - name: Create directories
        run: |
          mkdir -p ../../data/raw/mbajk

      - name: Run fetch data script
        run: |
          poetry run python src/data/fetch_data.py

      - name: Commit and push changes
        uses: actions/checkout@v4
        with:
          ref: develop
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git pull
            git diff-index --quiet HEAD || (git commit -a -m "Fetch data" --allow-empty)
            git push